// packages/react/src/toast.tsx
import { Toast, Toaster as ArkToaster, createToaster, type CreateToasterReturn } from '@ark-ui/react/toast'
import { forwardRef, type ComponentRef, type HTMLAttributes } from 'react'
import { toastVariants } from '@ui/core/recipes/toast'

export { createToaster }

type ToasterProps = {
  toaster: CreateToasterReturn
  className?: string
}

const Toaster = forwardRef<ComponentRef<typeof ArkToaster>, ToasterProps>(
  ({ className, toaster, ...props }, ref) => {
    const styles = toastVariants()
    return (
      <ArkToaster ref={ref} className={className} toaster={toaster} {...props}>
        {(toast) => (
          <Toast.Root className={styles.root({ class: toast.type === 'destructive' ? 'destructive' : undefined })}>
            <div className="grid gap-1">
              {toast.title && <Toast.Title className={styles.title()}>{toast.title}</Toast.Title>}
              {toast.description && <Toast.Description className={styles.description()}>{toast.description}</Toast.Description>}
            </div>
            <Toast.CloseTrigger className={styles.closeTrigger()}>✕</Toast.CloseTrigger>
            {toast.action && <Toast.ActionTrigger className={styles.actionTrigger()}>{toast.action?.label}</Toast.ActionTrigger>}
          </Toast.Root>
        )}
      </ArkToaster>
    )
  }
)
Toaster.displayName = 'Toaster'

export { Toaster, toastVariants }

// packages/solid/src/toast/index.tsx
import {
  Toaster as ArkToaster,
  createToaster,
  type CreateToasterReturn,
} from "@ark-ui/solid/toast";
import { splitProps, type Component } from "solid-js";
import { Toast as ToastBase } from "./toast.base";
import { type ToastVariants } from "@ui/core";
import { Portal } from "solid-js/web";

type ToasterProps = {
  toaster: CreateToasterReturn;
  class?: string;
};

const Toaster: Component<ToasterProps> = (props) => {
  const [local, others] = splitProps(props, ["class"]);
  return (
    <Portal>
      <ArkToaster class={local.class} {...others}>
        {(toast) => (
          <ToastBase.Root variant={(toast().type as ToastVariants["variant"]) || "default"}>
            <div class="grid gap-1">
              {toast().title && <ToastBase.Title>{toast().title}</ToastBase.Title>}
              {toast().description && (
                <ToastBase.Description>{toast().description}</ToastBase.Description>
              )}
            </div>
            <ToastBase.CloseTrigger>✕</ToastBase.CloseTrigger>
            {toast().action && (
              <ToastBase.ActionTrigger>{toast().action?.label}</ToastBase.ActionTrigger>
            )}
          </ToastBase.Root>
        )}
      </ArkToaster>
    </Portal>
  );
};

export { Toaster, createToaster, ToastBase };

export { toastVariants, type ToastVariants } from "@ui/core";
