// packages/solid/src/button.tsx
import { splitProps, type Component, type JSX } from 'solid-js'
import { buttonVariants } from '@ui/core'
import type { VariantProps } from 'tailwind-variants'

type ButtonProps = JSX.ButtonHTMLAttributes<HTMLButtonElement> &
  VariantProps<typeof buttonVariants>

const Button: Component<ButtonProps> = (props) => {
  const [local, others] = splitProps(props, ['class', 'variant', 'size'])
  return (
    <button
      class={buttonVariants({ variant: local.variant, size: local.size, class: local.class })}
      {...others}
    />
  )
}

export { Button, buttonVariants }

// packages/react/src/button.tsx
import { forwardRef, type ButtonHTMLAttributes } from 'react'
import { buttonVariants } from '@ui/core/recipes/button'
import type { VariantProps } from 'tailwind-variants'

type ButtonProps = ButtonHTMLAttributes<HTMLButtonElement> &
  VariantProps<typeof buttonVariants>

const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant, size, ...props }, ref) => {
    return (
      <button
        ref={ref}
        className={buttonVariants({ variant, size, class: className })}
        {...props}
      />
    )
  }
)
Button.displayName = 'Button'

export { Button, buttonVariants }
export type { ButtonProps }
