// packages/solid/src/combobox/index.tsx
import { Combobox as ComboboxBase } from "./combobox.base";
import type { Combobox as ArkCombobox } from "@ark-ui/solid/combobox";
import { Portal } from "solid-js/web";
import { splitProps, type Component, type JSX } from "solid-js";

const Combobox = ComboboxBase.Root;

const ComboboxLabel = ComboboxBase.Label;

type InputTriggerProps = ArkCombobox.InputProps;

const InputTrigger: Component<InputTriggerProps> = (props) => {
  const [local, others] = splitProps(props, ["class"]);
  return (
    <ComboboxBase.Control class={local.class}>
      <ComboboxBase.Input {...others} />
      <ComboboxBase.ClearTrigger>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
          class="size-4"
        >
          <path d="M18 6 6 18" />
          <path d="m6 6 12 12" />
        </svg>
      </ComboboxBase.ClearTrigger>
      <ComboboxBase.Trigger>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
          class="size-4"
        >
          <path d="m6 9 6 6 6-6" />
        </svg>
      </ComboboxBase.Trigger>
    </ComboboxBase.Control>
  );
};

type ContentProps = ArkCombobox.ContentProps & {
  class?: string;
  children?: JSX.Element;
};

const Content: Component<ContentProps> = (props) => {
  const [local, others] = splitProps(props, ["class", "children"]);
  return (
    <Portal>
      <ComboboxBase.Positioner>
        <ComboboxBase.Content class={local.class} {...others}>
          <ComboboxBase.List>{local.children}</ComboboxBase.List>
        </ComboboxBase.Content>
      </ComboboxBase.Positioner>
    </Portal>
  );
};

type ItemProps = ArkCombobox.ItemProps & { class?: string; children?: JSX.Element };

const Item: Component<ItemProps> = (props) => {
  const [local, others] = splitProps(props, ["class", "children"]);
  return (
    <ComboboxBase.Item class={local.class} {...others}>
      <ComboboxBase.ItemText>{local.children}</ComboboxBase.ItemText>
      <ComboboxBase.ItemIndicator>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
          class="size-4"
        >
          <path d="M20 6 9 17l-5-5" />
        </svg>
      </ComboboxBase.ItemIndicator>
    </ComboboxBase.Item>
  );
};

const ComboboxRootProvider = ComboboxBase.RootProvider;

const ComboboxInputTrigger = InputTrigger;
const ComboboxContent = Content;
const ComboboxItem = Item;

export {
  Combobox,
  ComboboxLabel,
  ComboboxInputTrigger,
  ComboboxContent,
  ComboboxItem,
  ComboboxRootProvider,
  ComboboxBase,
};
export { comboboxVariants, type ComboboxVariants } from "@ui/core";

// packages/react/src/combobox.tsx
import { Combobox, createListCollection } from "@ark-ui/react/combobox";
import { forwardRef, type ComponentRef } from "react";
import { comboboxVariants } from "@ui/core/recipes/combobox";

export { createListCollection };

export const ComboboxRoot = Combobox.Root;
export const ComboboxRootProvider = Combobox.RootProvider;
export const ComboboxLabel = Combobox.Label;

export const ComboboxControl = forwardRef<
  ComponentRef<typeof Combobox.Control>,
  Combobox.ControlProps & { className?: string }
>(({ className, children, ...props }, ref) => {
  const styles = comboboxVariants();
  return (
    <Combobox.Control ref={ref} className={styles.control({ class: className })} {...props}>
      {children}
      <Combobox.Trigger className={styles.trigger()}>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
          className="size-4"
        >
          <path d="m6 9 6 6 6-6" />
        </svg>
      </Combobox.Trigger>
    </Combobox.Control>
  );
});
ComboboxControl.displayName = "ComboboxControl";

export const ComboboxInput = Combobox.Input;
export const ComboboxTrigger = Combobox.Trigger;
export const ComboboxClearTrigger = Combobox.ClearTrigger;

export const ComboboxContent = forwardRef<
  ComponentRef<typeof Combobox.Content>,
  Combobox.ContentProps & { className?: string }
>(({ className, children, ...props }, ref) => {
  const styles = comboboxVariants();
  return (
    <Combobox.Positioner className={styles.positioner()}>
      <Combobox.Content ref={ref} className={styles.content({ class: className })} {...props}>
        {children}
      </Combobox.Content>
    </Combobox.Positioner>
  );
});
ComboboxContent.displayName = "ComboboxContent";

export const ComboboxList = forwardRef<
  ComponentRef<typeof Combobox.List>,
  Combobox.ListProps & { className?: string }
>(({ className, children, ...props }, ref) => {
  const styles = comboboxVariants();
  return (
    <Combobox.List ref={ref} className={styles.list({ class: className })} {...props}>
      {children}
    </Combobox.List>
  );
});
ComboboxList.displayName = "ComboboxList";

const ComboboxItem = forwardRef<
  ComponentRef<typeof Combobox.Item>,
  Combobox.ItemProps
>((props, ref) => {
  const styles = comboboxVariants();
  return (
    <Combobox.Item ref={ref} className={styles.item()} {...props}>
      <Combobox.ItemText className={styles.itemText()} />
      <Combobox.ItemIndicator className={styles.itemIndicator()}>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
          className="size-4"
        >
          <path d="M20 6 9 17l-5-5" />
        </svg>
      </Combobox.ItemIndicator>
    </Combobox.Item>
  );
});
ComboboxItem.displayName = "ComboboxItem";
export { ComboboxItem };

export const ComboboxItemText = Combobox.ItemText;
export const ComboboxItemIndicator = Combobox.ItemIndicator;

export { comboboxVariants };
