// packages/react/src/skeleton.tsx
import { forwardRef, type HTMLAttributes } from "react";
import { skeletonVariants } from "@ui/core/recipes/skeleton";

type SkeletonProps = HTMLAttributes<HTMLDivElement>;

const Skeleton = forwardRef<HTMLDivElement, SkeletonProps>(({ className, ...props }, ref) => {
  return <div ref={ref} className={skeletonVariants({ class: className })} {...props} />;
});
Skeleton.displayName = "Skeleton";

export { Skeleton, skeletonVariants };
export type { SkeletonProps };

// packages/solid/src/skeleton/index.tsx
import { splitProps, type Component } from "solid-js";
import { skeletonVariants } from "@ui/core";
import { ark, type HTMLArkProps } from "@ark-ui/solid/factory";

type SkeletonProps = HTMLArkProps<"div">;

const Skeleton: Component<SkeletonProps> = (props) => {
  const [local, others] = splitProps(props, ["class"]);
  return <ark.div class={skeletonVariants({ class: local.class })} {...others} />;
};

export { Skeleton, skeletonVariants };
