// packages/react/src/input.tsx
import { forwardRef, type InputHTMLAttributes } from 'react'
import { Field } from '@ark-ui/react/field'
import { inputVariants } from '@ui/core/recipes/input'

type InputProps = {
  label?: string
  description?: string
  error?: string
  className?: string
} & InputHTMLAttributes<HTMLInputElement>

const Input = forwardRef<HTMLInputElement, InputProps>(
  ({ label, description, error, className, ...props }, ref) => {
    const styles = inputVariants({ error: !!error })
    return (
      <Field.Root className={styles.root({ class: className })} invalid={!!error}>
        {label && <Field.Label className={styles.label()}>{label}</Field.Label>}
        <Field.Input className={styles.input()} ref={ref} {...props} />
        {description && !error && (
          <Field.HelperText className={styles.description()}>{description}</Field.HelperText>
        )}
        <Field.ErrorText className={styles.error()}>{error}</Field.ErrorText>
      </Field.Root>
    )
  }
)
Input.displayName = 'Input'

export { Input, inputVariants }
export type { InputProps }

// packages/solid/src/input.tsx
import { Field } from '@ark-ui/solid/field'
import { splitProps, type Component, type JSX } from 'solid-js'
import { inputVariants } from '@ui/core'

type InputProps = {
  label?: string
  description?: string
  error?: string
  class?: string
} & JSX.IntrinsicElements['input']

const Input: Component<InputProps> = (props) => {
  const [local, others] = splitProps(props, ['label', 'description', 'error', 'class'])
  const styles = inputVariants({ error: !!local.error })
  return (
    <Field.Root class={styles.root({ class: local.class })} invalid={!!local.error}>
      {local.label && <Field.Label class={styles.label()}>{local.label}</Field.Label>}
      <Field.Input class={styles.input()} {...others} />
      {local.description && !local.error && (
        <Field.HelperText class={styles.description()}>{local.description}</Field.HelperText>
      )}
      <Field.ErrorText class={styles.error()}>{local.error}</Field.ErrorText>
    </Field.Root>
  )
}

export { Input, inputVariants }
